# lightning.pytorch==2.2.1
# set seed here
seed_everything: 20010602
# trainer params
# undefined params will use default value
# if you are confused about params of trainer,
# please visit pytorch_lightning api
trainer:
  max_epochs: 100
  # params define early stopping
  callbacks:
    class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: 'val/epoch/acc'
      patience: 5
      mode: max
# params of model
model:
  in_features: 784
  hidden_dim: 128
  out_features: 10
  lr: 1e-4
  T_max: 100
  eta_min: 1e-6
# params of datamodule
data:
  data_dir: ./data_source
  batch_size: 128
  num_workers: 7
  val_size: 5000
