# lightning.pytorch==2.2.1
seed_everything: 20010602
trainer:
  max_epochs: 1000
model:
  in_features: 784
  hidden_dim: 512
  out_features: 10
  lr: 1e-4
  T_max: 100
data:
  data_dir: ./data
  batch_size: 64
  num_workers: 8
