# lightning.pytorch==2.2.1
seed_everything: 20010602
trainer:
  max_epochs: 100
model:
  in_features: 784
  hidden_dim: 512
  out_features: 10
  lr: 1e-4
  T_max: 100
data:
  data_dir: ./data_source
  batch_size: 32
  num_workers: 7
  val_size: 5000
